ALTER TABLE "OnboardingRequest"
ADD COLUMN IF NOT EXISTS "isLivingHere" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "UserFlatMembership"
ADD COLUMN IF NOT EXISTS "isLivingHere" BOOLEAN NOT NULL DEFAULT true;
